### ISSUE TITLE
UI features checklist

### ISSUE THREAD

**Issue by trillllian** [SMW-Editor/snes-iris#1]
just brainstorming right now, feel free to edit

(leaving all the parts that are only in the imgui version unchecked for now)

* [x] viewing disassembly
  * [ ] syntax highlighting? or at least *some* colors
  * [ ] highlight label
  * [ ] find all references to label
  * [ ] jump to address
  * [ ] jump to label definition
* [ ] editing
  * [x] add/edit/delete comment (only one per line, empty = no comment)
  * [ ] add label before line (works, but we should probably allow multiple labels per line)
  * [x] edit label
  * [ ] delete labels
  * [ ] edit asm arguments
* [ ] keyboard navigation
  * [ ] keep track of currently focused line, and allowed labels to be focused separately
  * [ ] vim-style motions for n lines up/down (is this overkill?) - if we add this, should also have something like vim's `relativenumber` to easily see where to jump to
  * [ ] shortcuts to add label before line, edit label, edit asm argument, edit comment
  * [ ] shortcut for jump to address

also we might want more stuff on one line? (merge multiple `db` commands, etc)

will have to consider how the editor UI works in that case (especially when there are multiple editable things on one line)
