### ISSUE TITLE
disassembler features / disassembly format checklist

### ISSUE THREAD

**Issue by trillllian** [SMW-Editor/snes-iris#2]
* [ ] allow merging multiple db statements onto one line - possibly with more rules?
  * [ ] allow treating a merged db line as a string literal (not sure how often this would be used?)
* [ ] autoconvert `db $ff,$ff,$ff,...` into `fill` commands
* [ ] manually replace an address range with specified code (e.g. for loops)
* [ ] some way to have comments on labels
* [ ] replace specific sequences of instructions with macro calls

what else do we want the disassembly to have??
